# See: https://www.dartlang.org/tools/pub/pubspec
name: flutter_lua
version: 0.3.1
description: >-
  Lua interpreter and runtime for executing dynamic scripts in Flutter apps.
homepage: https://github.com/drydart/flutter_lua
documentation:
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
dependency_overrides:
environment:
  sdk: '>=3.3.0 <4.0.0'
executables:
flutter:
  plugin:
    androidPackage: com.github.drydart.flutter_lua
    pluginClass: FlutterLuaPlugin
